// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    else if (defaultTargetPlatform == TargetPlatform.iOS || defaultTargetPlatform == TargetPlatform.macOS) {
      return ios;
    } 
    else {
      throw UnsupportedError(
        'DefaultFirebaseOptions are not supported for this platform.',
      );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh2tuUoiTrHxlXqMq8cszdZ8OyPlgrT6U',
    appId: '1:523363027388:web:3c46eaf192c035377803b9',
    messagingSenderId: '523363027388',
    projectId: 'dovewing-a55c5',
    authDomain: 'dovewing-a55c5.firebaseapp.com',
    storageBucket: 'dovewing-a55c5.appspot.com',
    measurementId: 'G-B1J034M4SV',
  );

   static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYX0euBMDUcI0VKEs5dSFe3KbtdFrbNUc',
    appId: '1:523363027388:ios:e6297204056a4e897803b9',
    messagingSenderId: '523363027388',
    projectId: 'dovewing-a55c5',
    storageBucket: 'dovewing-a55c5.appspot.com',
    iosBundleId: 'com.example.dovewing',
  );

}